### ISSUE TITLE
GitHub Actions für CI

### ISSUE THREAD

**Issue by almereyda** [openjverein/jverein#39]
@tobidope hat in #9 vorgeschlagen, die Anwendung in GitHub Actions zu bauen, von wo aus sie sich auch automatisch releasen ließen. Siehe dazu auch diesen PR von @willuhn:

- #35

Hier können wir über Experimente und Fortschritte dazu sprechen.

**Comment by almereyda** [comment]
Beispiele:

* https://github.com/willuhn/jameica/pull/37
* https://github.com/willuhn/hibiscus/pull/76

**Comment by dippeal** [comment]
Hi,
ich habe mich etwas mit den github action probiert. Ziel soll es erstmal sein ein ant build zu erstellen. Leider findet das javac beim compilieren die classes von jameica nicht. Bevor ich das build mache lade ich die sourcen von jameica und hibiscus und baue eine Ordnerstruktur analog zu meiner Entwicklungsumgebung auf. Trotzdem werden die Klassen nicht gefunden/geladen.

_**Hat jemand eine Idee?**_

Hier meine ant.yml:
```
# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: openjverein build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Set up JDK 11 for x64
      uses: actions/setup-java@main
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64

    - name: Checkout master
      uses: actions/checkout@main
      with:
        path: jverein
    
    - name: Check out jameica
      uses: actions/checkout@main
      with:
        repository: willuhn/jameica
        token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
        path: jameica
    
    - name: Check out hibiscus
      uses: actions/checkout@main
      with:
        repository: willuhn/hibiscus
        token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
        path: hibiscus
    
    - name: Show Working directory
      run: pwd && ls
        
    - name: Build with Ant
      working-directory: ./
      run: pwd && ant -noinput -buildfile jverein/build/build.xml

``` 

Ordnerstruktur (Show Working directory):
```
/home/runner/work/jverein/jverein
hibiscus
jameica
jverein
``` 

Fehlermeldung:

```
pwd && ant -noinput -buildfile jverein/build/build.xml

/home/runner/work/jverein/jverein
Buildfile: /home/runner/work/jverein/jverein/jverein/build/build.xml

init:
     [echo] VERSION: 2.8.20
     [echo] BUILD  : 52[3](https://github.com/dippeal/jverein/actions/runs/6922332922/job/18828934383#step:7:3)
     [echo] JAVA   : 11.0.21

clean:

compile:
    [mkdir] Created dir: /home/runner/work/jverein/jverein/jverein/bin
    [javac] Compiling 805 source files to /home/runner/work/jverein/jverein/jverein/bin
    [javac] /home/runner/work/jverein/jverein/jverein/src/de/jost_net/JVerein/Calendar/MitgliedAppointmentProvider.java:33: error: package de.willuhn.jameica.gui.calendar does not exist
    [javac] import de.willuhn.jameica.gui.calendar.Appointment;
    [javac]                                       ^
    [javac] /home/runner/work/jverein/jverein/jverein/src/de/jost_net/JVerein/Calendar/MitgliedAppointmentProvider.java:3[4](https://github.com/dippeal/jverein/actions/runs/6922332922/job/18828934383#step:7:4): error: package de.willuhn.jameica.gui.calendar does not exist
    [javac] import de.willuhn.jameica.gui.calendar.AppointmentProvider;
    [javac]                                       ^
    [javac] /home/runner/work/jverein/jverein/jverein/src/de/jost_net/JVerein/Calendar/MitgliedAppointmentProvider.java:3[5](https://github.com/dippeal/jverein/actions/runs/6922332922/job/18828934383#step:7:5): error: package de.willuhn.jameica.system does not exist
    [javac] import de.willuhn.jameica.system.Settings;
    [javac]                                 ^
    [javac] /home/runner/work/jverein/jverein/jverein/src/de/jost_net/JVerein/Calendar/MitgliedAppointmentProvider.java:42: error: cannot find symbol
    [javac] public class MitgliedAppointmentProvider implements AppointmentProvider
```
